steps:
  # Build the API Gateway container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_IMAGE_NAME}',
      '-f', 'services/api-gateway/Dockerfile',
      '.'
    ]

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_IMAGE_NAME}'
    ]

  # Deploy to Cloud Run with Secret Manager integration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-gateway'
      - '--image'
      - '${_IMAGE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'sentilyze-ai-agents@${_PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'JWT_SECRET=JWT_SECRET:latest,GOLDAPI_API_KEY=GOLDAPI_API_KEY:latest,COINMARKETCAP_API_KEY=COINMARKETCAP_API_KEY:latest,REDDIT_CLIENT_ID=REDDIT_CLIENT_ID:latest,REDDIT_CLIENT_SECRET=REDDIT_CLIENT_SECRET:latest'
      - '--set-env-vars'
      - 'ENVIRONMENT=${_ENVIRONMENT},PROJECT_ID=${_PROJECT_ID},PUBSUB_PROJECT_ID=${_PROJECT_ID},FEATURE_GOLD_ROUTES=true,FEATURE_CRYPTO_ROUTES=true'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - '${_IMAGE_NAME}'

substitutions:
  _IMAGE_NAME: 'gcr.io/sentilyze-v6-clean/api-gateway'
  _REGION: 'us-central1'
  _ENVIRONMENT: 'production'
  _PROJECT_ID: 'sentilyze-v6-clean'

options:
  logging: CLOUD_LOGGING_ONLY

tags:
  - sentilyze
  - api-gateway
  - cloud-run
  - secret-manager
