"""Add feature flags table.

Revision ID: 20260131_002
Revises: 20260131_001
Create Date: 2026-01-31 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260131_002'
down_revision: Union[str, None] = '20260131_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('cost_impact_daily_usd', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_category'), 'feature_flags', ['category'], unique=False)
    op.create_index(op.f('ix_feature_flags_enabled'), 'feature_flags', ['enabled'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    
    op.create_table('feature_flag_audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('flag_key', sa.String(length=100), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('changed_by', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['changed_by'], ['admin_users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flag_audit_logs_flag_key'), 'feature_flag_audit_logs', ['flag_key'], unique=False)
    
    # Insert initial feature flags
    op.execute("""
        INSERT INTO feature_flags (key, name, description, enabled, cost_impact_daily_usd, category) VALUES
        ('ENABLE_REAL_TIME_WEBSOCKET', 'Real-time WebSocket', 'Live data streaming via WebSocket', false, 25.00, 'infrastructure'),
        ('ENABLE_ML_PREDICTIONS', 'ML Predictions', 'LSTM/ARIMA/RF ensemble predictions', false, 50.00, 'ml'),
        ('ENABLE_SOCIAL_SCRAPING', 'Social Media Scraping', 'Twitter/Reddit data collection', false, 80.00, 'data'),
        ('ENABLE_BIGQUERY_STREAMING', 'BigQuery Streaming', 'Real-time BigQuery inserts', false, 20.00, 'infrastructure'),
        ('ENABLE_ADVANCED_ANALYTICS', 'Advanced Analytics', 'Complex BigQuery analytics queries', false, 15.00, 'analytics'),
        ('ENABLE_GOLD_DATA', 'Gold Data Sources', 'GoldAPI and metal data feeds', false, 10.00, 'data'),
        ('ENABLE_CRYPTO_DATA', 'Crypto Data Sources', 'Binance and crypto feeds', false, 15.00, 'data'),
        ('CACHE_TTL_SECONDS', 'Cache TTL', 'Cache duration in seconds', false, 0.00, 'performance');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flag_audit_logs_flag_key'), table_name='feature_flag_audit_logs')
    op.drop_table('feature_flag_audit_logs')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_enabled'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_category'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
